version: '3.8'

services:
  services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=newpassword
      - MYSQL_DATABASE=back
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  spring-app:
    image: your-spring-boot-app:latest
    build:
      context: ./back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/back
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=newpassword
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  react-app:
    build:
      context: ./client  # Assuming your React app is in the 'react' directory relative to the docker-compose.yml file
    dockerfile: Dockerfile
    ports:
      - "3000:3000"  # React app will run on port 3000
    depends_on:
      - spring-app
    networks:
      - app-network

volumes:
  mysql-data:
